language: python, cpp
dist: trusty
branches:
  only:
    - newMaster
python:
  - "2.7"
compiler:
  - gcc
notifications:
  email:
    recipients:
      - gladk@debian.org
    on_success: change
    on_failure: always
before_script:
  - pip install -I numpy==1.8.2
  - python -c 'import numpy; print numpy.version.version'
  - sudo bash -c 'echo "deb http://www.yade-dem.org/packages/ trusty/" >> /etc/apt/sources.list'
  - wget -O - http://www.yade-dem.org/packages/yadedev_pub.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake debhelper freeglut3-dev help2man ipython python-numpy libboost-all-dev libbz2-dev libcgal-dev libeigen3-dev libgl1-mesa-dev  python-argparse python-gts python-imaging python-matplotlib python-minieigen python-qt4 python-support python-tk python-xlib python-bibtex python-sphinx libgts-dev libloki-dev libmetis-dev libopenblas-dev libqglviewer-dev libsuitesparse-dev libvtk5-dev libxi-dev libxmu-dev pyqt4-dev-tools python-all-dev  zlib1g-dev dvipng graphviz libjs-jquery lmodern texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended texlive-pictures texlive-xetex tipa
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./../inst -DSUFFIX=-trunk ..
script:
  - make
  - make install
  - ./../inst/bin/yade-trunk --test
  - ./../inst/bin/yade-trunk --check
